server:
  context-path: /user
  port: 9000


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://193.112.60.111/user?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 1
    maxActive: 20
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  redis:
      host: 111.230.182.190
      port: 6379
  freemarker:
    settings:
      auto_import: ftl/common/config/top.ftl as _top,ftl/common/config/left.ftl as _left
    check-template-location: false
    enabled: true
    cache: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp





