server:
  context-path: /user
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/user?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 1
    maxActive: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
      host: 192.168.247.128
      port: 6379
  thymeleaf:
    check-template: false
    cache: false
    mode: LEGACYHTML5

